/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webagesolutions_jni_Multiplier */

#ifndef _Included_com_webagesolutions_jni_Multiplier
#define _Included_com_webagesolutions_jni_Multiplier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webagesolutions_jni_Multiplier
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_webagesolutions_jni_Multiplier_multiply
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
